# Site settings
title: "Documentation"
description: "Documentation for Digital Tools"
url: "https://byandell.github.io"
baseurl: "/Documentation"

plugins:
  - jekyll-relative-links
  - jekyll-remote-theme
relative_links:
  enabled: true
  collections: true
nav_external_links:
  - title: Documentation GitHub
    url: https://github.com/byandell/Documentation
    hide_icon: false # set to true to hide the external link icon - defaults to false
    opens_in_new_tab: true # set to true to open this link in a new tab - defaults to false
include:
  - verde_models.csv

remote_theme: just-the-docs/just-the-docs

exclude:
  - "**/*.qmd"
  - "site_libs/*"

defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: default